### ISSUE TITLE
Investigate issue with node not shutting down peer connection properly causing the shutdown sequence to hang.

### ISSUE THREAD

**Issue by fassadlr** [stratisproject/StratisBitcoinFullNode#2861]
Logs are in #2790

**Comment by sondreb** [comment]
Can confirm this problem, and I hit it during debugging so I was able to perform the "Break All", here are some details:

![image](https://user-images.githubusercontent.com/309938/49483814-ef34c180-f834-11e8-8602-a5822d5a17d1.png)

This is where it hangs:

![image](https://user-images.githubusercontent.com/309938/49483822-fb208380-f834-11e8-9204-1e8faa4864da.png)

this.IsConnected is at breakpoint set to false.

Not sure if the above is the exact spot where the problem is, as I continued and paused a bit and there are a few awaits, here are my stack:

![image](https://user-images.githubusercontent.com/309938/49483993-ab8e8780-f835-11e8-9886-d068f1405581.png)

From Stackoverflow:

![image](https://user-images.githubusercontent.com/309938/49484319-e1803b80-f836-11e8-8a47-68dff157a672.png)

https://stackoverflow.com/a/40855230/240382

That is not the cause of the issue though, just that it ends up with a deadlock.

**Comment by sondreb** [comment]
Problem repeated itself, this time break all ends up here:

![image](https://user-images.githubusercontent.com/309938/49484837-bb5b9b00-f838-11e8-8648-abf1e4397035.png)

Last console log entry is still:

```
Waiting for PeerConnectorAddNode.ConnectAsync to finish.
```

**Comment by sondreb** [comment]
I realize that this ConnectAsync method is only something that is called if -addnode is used, so this behavior I have might be something different than the original issue.

**Comment by sondreb** [comment]
Actually not only related to addnode:

```
info: Stratis.Bitcoin.FullNode[0]
      Waiting for DiscoverPeersAsync to finish.
info: Stratis.Bitcoin.FullNode[0]
      DiscoverPeersAsync stopping.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeerConnectorAddNode.ConnectAsync to finish.
info: Stratis.Bitcoin.FullNode[0]
      Waiting for PeerConnectorDiscovery.ConnectAsync to finish.
````

**Comment by dangershony** [comment]
I get this issue as well quite often we need to investigate this.

**Comment by maciejzaleski** [comment]
This might be related to #2918

**Comment by noescape00** [comment]
Fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/2922

**Comment by fassadlr** [comment]
I have observed this issue again on Sunday so re-opening for further investigation.

**Comment by noescape00** [comment]
@fassadlr if you heave trace logs for the new occurrence of this bug please share

**Comment by fassadlr** [comment]
@sondreb Have you been able to reproduce this? Or is it a random occurrence.

**Comment by sondreb** [comment]
I can confirm that this is still an issue:

Hanged here just now:

```
[2018-12-11 00:58:53.1254 15] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.Dispose Waiting for PeerConnectorDiscovery.ConnectAsync to finish.
```

I did not let the daemon run very long, it had a few connections (2 I think), but it was throwing a lot of exceptions attempting to connect to a lot of different nodes.

**Comment by fassadlr** [comment]
OK I've managed to get a further with this!

It appears that the shut down sequence itself is not the issue. The deadlock actually happens whilst running the node.

When the node state changes to `Handshaked` we call `NetworkPeer.SetStateAsync` on a thread. The node then starts sending Payload messages to the other connected node. If anything goes wrong in `NetworkPeerConnection.SendAsync` for example an `OperationCanceledException` gets thrown, we will try and disconnect the peer. This will ALSO try and set the network peer's state by calling ``NetworkPeer.SetStateAsync` and a deadlock happens. This is because the same thread is trying to set its state to `Handshaked` as well as `Disconnecting`.

A possible fix will be to run `peer.Disconnect` in a Task here:

```
            catch (OperationCanceledException)
            {
                this.peer.Disconnect("Connection to the peer has been terminated");
                this.logger.LogTrace("(-)[CANCELED_EXCEPTION]");
                throw;
            }
```

in NetworkPeer's `SendAsync` method. Further investigation is needed.

**Comment by dangershony** [comment]
I confirm I managed to reproduce this by throwing a `OperationCanceledException`


This is currently idenfied to happen at the `ConnectionManagerBehavior` when sending `SendHeadersPayload`


A dirty change that will fix this immediately is this

```
   Task.Run(async () =>
                    {
                        await peer.SendMessageAsync(new SendHeadersPayload()).ConfigureAwait(false);
                    });
```

However we should consider using an `AsyncQueue` when calling disconnect in the `PeerConnector`
