### ISSUE TITLE
[PeerConnector] System.OperationCanceledException is thrown all the time

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/StratisBitcoinFullNode#968]
The following 3 methods are continuously generating System.OperationCanceledException exceptions:
`Stratis.Bitcoin.P2P.Peer.NetworkPeerClient.ConnectAsync`
`Stratis.Bitcoin.P2P.Peer.NetworkPeerFactory.CreateConnectedNetworkPeerAsync`
`Stratis.Bitcoin.P2P.PeerConnector.ConnectAsync`

> Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
> Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
> Exception thrown: 'System.OperationCanceledException' in Stratis.Bitcoin.dll
> Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
> Exception thrown: 'System.OperationCanceledException' in Stratis.Bitcoin.dll
> Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
> Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll

I'm not sure of the root reason yet, are they normal?
They should probably be handled in a different way if they are so frequent.

**Comment by andrasfuchs** [comment]
I've just realized that it's probably fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/959#pullrequestreview-84795754

**Comment by Aprogiena** [comment]
it is likely fixed by that, but it was never a bug (in our code), see discussion in #928 and if you are satisfied, feel free to close the issue

**Comment by andrasfuchs** [comment]
I have the settings you recommend in #928, but my output is still flooded with debug messages about the exceptions. If I enable tracing it is the same thing in the log file. 

![image](https://user-images.githubusercontent.com/910321/34255229-f32abd82-e64f-11e7-9865-2cf0c1f347fe.png)

So I would still say that something is still wrong, but it might be a problem with my network configuration (I use VPN for example). 

I can see a lot of messages like these:
> Error connecting to '[2001:0:9d38:6abd:18b0:3071:4fd7:3576]:26178', exception: A socket operation was attempted to an unreachable network [2001:0:9d38:6abd:18b0:3071:4fd7:3576]:26178

> Error connecting to '[::ffff:98.229.142.125]:26178', exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): No connection could be made because the target machine actively refused it [::ffff:98.229.142.125]:26178

My impression is that the node tries to reach an unreachable peer again and again, and as we collect more potential peer addresses the number of unreachable peers rises too, so the number of exceptions thrown as well.

**Comment by Aprogiena** [comment]
this is expected as discussed on slack
